// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtFBVYArhbspyM722hSa0WN-bQT_CM6X0',
    appId: '1:902926438376:web:791420f50992f7ef595e5d',
    messagingSenderId: '902926438376',
    projectId: 'mynotes-app-020',
    authDomain: 'mynotes-app-020.firebaseapp.com',
    storageBucket: 'mynotes-app-020.firebasestorage.app',
    measurementId: 'G-NDGCME0PK2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiyPoQ8JXeHIl_2LvQmNvOQzi7OVPkqmU',
    appId: '1:902926438376:android:7d161200c3af21a6595e5d',
    messagingSenderId: '902926438376',
    projectId: 'mynotes-app-020',
    storageBucket: 'mynotes-app-020.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaQcLASP8sdZk6PmvbJ1vCRQUeKHHqK4E',
    appId: '1:902926438376:ios:b74ea8b023eed5a4595e5d',
    messagingSenderId: '902926438376',
    projectId: 'mynotes-app-020',
    storageBucket: 'mynotes-app-020.firebasestorage.app',
    iosBundleId: 'com.example.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaQcLASP8sdZk6PmvbJ1vCRQUeKHHqK4E',
    appId: '1:902926438376:ios:b74ea8b023eed5a4595e5d',
    messagingSenderId: '902926438376',
    projectId: 'mynotes-app-020',
    storageBucket: 'mynotes-app-020.firebasestorage.app',
    iosBundleId: 'com.example.mynotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaQcLASP8sdZk6PmvbJ1vCRQUeKHHqK4E',
    appId: '1:902926438376:web:cdf70927c962d544595e5d',
    messagingSenderId: '902926438376',
    projectId: 'mynotes-app-020',
    authDomain: 'mynotes-app-020.firebaseapp.com',
    storageBucket: 'mynotes-app-020.firebasestorage.app',
    measurementId: 'G-Q14RNSBDS2',
  );
}
